name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.6

      - name: Installing Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo npm install -g csvtojson@2.0.10
          sudo npm install -g prettier@3.3.3

      - name: Generate
        run: |
          chmod +x ./generate.sh
          ./generate.sh

      - name: Run Python Program
        run: ./IMDb.py

      - name: Prettify files
        run: |
          prettier --write .
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit files
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"

      - name: Push changes
        if: steps.check_changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
