name: PR Check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js environment
        uses: actions/setup-node@v7.0.0

      - name: Setup Python environment
        uses: actions/setup-python@v7
        with:
          python-version: 3.14.6

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable

      - name: Installing Dependencies
        run: |
          pip install --upgrade pipenv
          pipenv install

      - name: Generate
        run: |
          chmod +x ./generate.sh
          pipenv run ./generate.sh

      - name: Prettify files
        run: |
          npx prettier@3.5.3 --write .

      - name: Check for changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "Nothing to update."
          else
            echo "File(s) changed -"
            git diff --name-only
          fi
